In [2]:
# Cell 1: Q1 - Manual Hyperparameter Tuning for KNN
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Train-Test Split (test_size=0.33, random_state=42)
X_train_q1, X_test_q1, y_train_q1, y_test_q1 = train_test_split(
    X, y, test_size=0.33, random_state=42
)

# Try different values of n_neighbors
n_neighbors_list = [3, 5, 7, 11, 13, 15]
knn_scores = {}

print("=== Q1: KNN Manual Tuning Scores ===")
for k in n_neighbors_list:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_q1, y_train_q1)
    score = knn.score(X_test_q1, y_test_q1)
    knn_scores[k] = score
    print(f"n_neighbors = {k:2d} | Test Score: {score:.4f}")

# Highest accuracy
best_k = max(knn_scores, key=knn_scores.get)
print(f"\nResult: n_neighbors = {best_k} gave the highest accuracy of {knn_scores[best_k]:.4f}")

=== Q1: KNN Manual Tuning Scores ===
n_neighbors =  3 | Test Score: 0.9800
n_neighbors =  5 | Test Score: 0.9800
n_neighbors =  7 | Test Score: 0.9800
n_neighbors = 11 | Test Score: 1.0000
n_neighbors = 13 | Test Score: 1.0000
n_neighbors = 15 | Test Score: 1.0000

Result: n_neighbors = 11 gave the highest accuracy of 1.0000

In [5]:
# Cell 2: Q2 - Manual Hyperparameter Tuning for SVM
from sklearn.svm import SVC

C_values = [1, 10, 20]
kernels = ['linear', 'rbf']
svm_scores = {}

print("=== Q2: SVM Manual Tuning Scores ===")
for C in C_values:
    for kernel in kernels:
        svm = SVC(C=C, kernel=kernel)
        svm.fit(X_train_q1, y_train_q1)
        score = svm.score(X_test_q1, y_test_q1)
        svm_scores[(C, kernel)] = score
        print(f"C = {C:2d} | Kernel = {kernel:<6s} | Test Accuracy: {score:.4f}")

best_svm = max(svm_scores, key=svm_scores.get)
print(f"\nResult: Best combination is C={best_svm[0]} and kernel='{best_svm[1]}' with accuracy {svm_scores[best_svm]:.4f}")

=== Q2: SVM Manual Tuning Scores ===
C =  1 | Kernel = linear | Test Accuracy: 1.0000
C =  1 | Kernel = rbf    | Test Accuracy: 1.0000
C = 10 | Kernel = linear | Test Accuracy: 1.0000
C = 10 | Kernel = rbf    | Test Accuracy: 0.9800
C = 20 | Kernel = linear | Test Accuracy: 0.9800
C = 20 | Kernel = rbf    | Test Accuracy: 1.0000

Result: Best combination is C=1 and kernel='linear' with accuracy 1.0000

In [6]:
# Cell 3: Q3 - Grid Search CV on SVM
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [1, 10, 20],
    'kernel': ['linear', 'rbf']
}

grid_svm = GridSearchCV(SVC(), param_grid, cv=5)
grid_svm.fit(X_train_q1, y_train_q1)

# Results DataFrame
grid_results = pd.DataFrame(grid_svm.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

print("=== Q3: GridSearchCV Results Table ===")
display(grid_results)

print(f"Best Parameters : {grid_svm.best_params_}")
print(f"Best Score      : {grid_svm.best_score_:.4f}")

=== Q3: GridSearchCV Results Table ===

   param_C param_kernel  mean_test_score
0        1       linear             0.95
1        1          rbf             0.93
2       10       linear             0.93
3       10          rbf             0.94
4       20       linear             0.93
5       20          rbf             0.95

Best Parameters : {'C': 1, 'kernel': 'linear'}
Best Score      : 0.9500

In [7]:
# Cell 4: Q4 - Randomized Search CV on SVM
from sklearn.model_selection import RandomizedSearchCV

random_svm = RandomizedSearchCV(SVC(), param_distributions=param_grid, n_iter=5, cv=5, random_state=42)
random_svm.fit(X_train_q1, y_train_q1)

# Results DataFrame
random_results = pd.DataFrame(random_svm.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

print("=== Q4: RandomizedSearchCV Results Table ===")
display(random_results)

print(f"Random Search Best Parameters : {random_svm.best_params_}")
print(f"Random Search Best Score      : {random_svm.best_score_:.4f}")

print("\n--- Comparison with Grid Search ---")
print(f"Grid Search Best Params       : {grid_svm.best_params_} | Score: {grid_svm.best_score_:.4f}")
print(f"Random Search Best Params     : {random_svm.best_params_} | Score: {random_svm.best_score_:.4f}")

=== Q4: RandomizedSearchCV Results Table ===

   param_C param_kernel  mean_test_score
0        1       linear             0.95
1        1          rbf             0.93
2       20          rbf             0.95
3       10       linear             0.93
4       20       linear             0.93

Random Search Best Parameters : {'kernel': 'linear', 'C': 1}
Random Search Best Score      : 0.9500

--- Comparison with Grid Search ---
Grid Search Best Params       : {'C': 1, 'kernel': 'linear'} | Score: 0.9500
Random Search Best Params     : {'kernel': 'linear', 'C': 1} | Score: 0.9500

In [8]:
# Cell 5: Q5 - Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# New Train-Test Split (test_size=0.2, stratify=y)
X_train_q5, X_test_q5, y_train_q5, y_test_q5 = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_q5, y_train_q5)

rf_pred = rf_model.predict(X_test_q5)
rf_acc = accuracy_score(y_test_q5, rf_pred)

print(f"Q5 - Random Forest Test Accuracy: {rf_acc:.4f}")

Q5 - Random Forest Test Accuracy: 0.9000

In [9]:
# Cell 6: Q6 - AdaBoost and Gradient Boosting
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

# 1. AdaBoost
ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)
ada_model.fit(X_train_q5, y_train_q5)
ada_acc = accuracy_score(y_test_q5, ada_model.predict(X_test_q5))

# 2. Gradient Boosting
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
gb_model.fit(X_train_q5, y_train_q5)
gb_acc = accuracy_score(y_test_q5, gb_model.predict(X_test_q5))

print(f"Q6 - AdaBoost Classifier Accuracy        : {ada_acc:.4f}")
print(f"Q6 - Gradient Boosting Classifier Accuracy: {gb_acc:.4f}")

Q6 - AdaBoost Classifier Accuracy        : 0.9333
Q6 - Gradient Boosting Classifier Accuracy: 0.9667

In [18]:
import sys
!{sys.executable} -m pip install xgboost

Collecting xgboost
  Using cached xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from xgboost) (2.5.1)
Requirement already satisfied: scipy in c:\users\asus\appdata\local\python\pythoncore-3.12-64\lib\site-packages (from xgboost) (1.18.0)
Using cached xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0

WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
# Cell 7: Q7 - XGBoost Classifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

xgb_model = XGBClassifier(
    n_estimators=100, 
    learning_rate=0.1, 
    max_depth=3, 
    random_state=42
)
xgb_model.fit(X_train_q5, y_train_q5)

xgb_pred = xgb_model.predict(X_test_q5)
xgb_acc = accuracy_score(y_test_q5, xgb_pred)

print(f"Q7 - XGBoost Classifier Accuracy: {xgb_acc:.4f}")

Q7 - XGBoost Classifier Accuracy: 0.9333

In [20]:
# Cell 8: Q8 - GridSearchCV on Random Forest
rf_param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [3, 5, 7]
}

rf_grid = GridSearchCV(RandomForestClassifier(random_state=42), rf_param_grid, cv=5)
rf_grid.fit(X_train_q5, y_train_q5)

print("=== Q8: Random Forest Grid Search ===")
print(f"Best Parameters : {rf_grid.best_params_}")
print(f"Best CV Score   : {rf_grid.best_score_:.4f}")

=== Q8: Random Forest Grid Search ===
Best Parameters : {'max_depth': 3, 'n_estimators': 50}
Best CV Score   : 0.9583

In [22]:
# Cell 9: Q9 - Model Comparison Table
models = {
    'SVM (Best Grid Search)': SVC(C=1, kernel='linear', random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42),
    'AdaBoost': AdaBoostClassifier(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42),
    'XGBoost': XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
}

comparison_data = []

for name, model in models.items():
    model.fit(X_train_q5, y_train_q5)
    acc = accuracy_score(y_test_q5, model.predict(X_test_q5))
    comparison_data.append({'Model': name, 'Accuracy Score': f"{acc * 100:.2f}%"})

comparison_df = pd.DataFrame(comparison_data)

print("=== Q9: Model Comparison Table ===")
display(comparison_df)
print("Conclusion: All models achieved between 96.67% and 100% accuracy on the test set due to" \
" the high class separability of the Iris dataset.")

=== Q9: Model Comparison Table ===

                    Model Accuracy Score
0  SVM (Best Grid Search)        100.00%
1           Random Forest         96.67%
2                AdaBoost         93.33%
3       Gradient Boosting         96.67%
4                 XGBoost         93.33%

Conclusion: All models achieved between 96.67% and 100% accuracy on the test set due to the high class separability of the Iris dataset.